import { getAIProvider } from "@/src/lib/ai/provider";
import { knowledgeReadiness, getVerifiedRelevantKnowledge } from "@/src/lib/business-knowledge/service";
import { decideReply } from "@/src/lib/reply-decision/service";
import { supabaseRequest } from "@/src/lib/supabase/server";
import type { AutoReplyResult, AutoReplySettings } from "./types";

const defaults: AutoReplySettings = { auto_reply_enabled: false, auto_reply_dry_run: true, auto_reply_min_confidence: 0.95, allowed_auto_safe_intents: [] };
const scope = "app_id=eq.sales_copilot";
export async function getAutoReplySettings(): Promise<AutoReplySettings> { const rows = await supabaseRequest<Array<{ payload: Partial<AutoReplySettings> }>>(`sales_settings?${scope}&kind=eq.reply_policy&select=payload&limit=1`); return { ...defaults, ...(rows[0]?.payload || {}) }; }
export async function updateAutoReplySettings(patch: Partial<AutoReplySettings>) { const current = await getAutoReplySettings(); const payload = { ...current, ...patch, auto_reply_min_confidence: Math.max(0, Math.min(1, Number(patch.auto_reply_min_confidence ?? current.auto_reply_min_confidence))), allowed_auto_safe_intents: Array.isArray(patch.allowed_auto_safe_intents) ? patch.allowed_auto_safe_intents.filter(v => typeof v === "string") : current.allowed_auto_safe_intents }; const rows = await supabaseRequest<Array<{ payload: AutoReplySettings }>>(`sales_settings?${scope}&kind=eq.reply_policy`, { method: "PATCH", body: JSON.stringify({ payload, updated_at: new Date().toISOString() }) }); return rows[0]?.payload || payload; }
const hardBlocked = new Set(["commercial_negotiation", "guarantee_or_capability_promise", "legal_or_contract", "payment_or_refund_dispute", "complaint_or_threat", "partnership_or_collaboration", "real_commitment_scheduling", "not_interested", "unsupported_capability"]);
function allowedIntent(intent: string, allowed: string[]) { const aliases: Record<string, string[]> = { capability_faq: ["faq", "platform_support", "simple_capability_question"], acknowledgement: ["acknowledgement"] }; return allowed.includes(intent) || (aliases[intent] || []).some(value => allowed.includes(value)); }
function validateText(text: string, knowledge: { context: string }, intent: string) { const lower = text.toLowerCase(); const unsupported = [/\b\d+[,.]?\d*\s*(eur|usd|лв|€|\$)/i, /\b(discount|off|discounts|отстъп)/i, /\b(guarantee|guaranteed|гарант)/i, /\b(refund|contract|terms|policy|timeline|days|седмиц|договор)/i]; if (unsupported.some(pattern => pattern.test(text))) return "Generated text contains a gated factual or commercial claim."; if ((/instagram|platform|support|поддърж/i.test(lower) || intent === "capability_faq") && !knowledge.context) return "Generated capability claim has no verified knowledge backing."; return null; }
export async function evaluateAutoReply(input: { message: string; leadId?: string; messageId?: string; conversationId?: string; dryRun?: boolean }): Promise<AutoReplyResult> {
  if (input.messageId) { const prior = await supabaseRequest<Array<{ id: string; status: string }>>(`sales_auto_replies?${scope}&inbound_message_id=eq.${encodeURIComponent(input.messageId)}&select=id,status&limit=1`); if (prior[0]) return { eligible: false, reason: "This inbound message has already been processed.", failedGates: ["idempotency"], logId: prior[0].id }; }
  const settings = await getAutoReplySettings(); const decision = await decideReply({ message: input.message, leadId: input.leadId, messageId: input.messageId }); const readiness = await knowledgeReadiness(decision.intent, input.message); const failed: string[] = []; if (!settings.auto_reply_enabled) failed.push("auto_reply_disabled"); if (decision.mode !== "AUTO_SAFE") failed.push("decision_not_auto_safe"); if (!allowedIntent(decision.intent, settings.allowed_auto_safe_intents)) failed.push("intent_not_allowed"); if (decision.confidence < settings.auto_reply_min_confidence) failed.push("confidence_below_threshold"); if (decision.riskFlags.length) failed.push("risk_flags"); if (!readiness.eligible) failed.push("missing_verified_knowledge"); if (hardBlocked.has(decision.intent)) failed.push("hard_blocked_intent"); if (failed.length) { const row = await supabaseRequest<Array<{ id: string }>>("sales_auto_replies", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", conversation_id: input.conversationId || null, inbound_message_id: input.messageId || null, decision_mode: decision.mode, intent: decision.intent, confidence: decision.confidence, knowledge_refs: readiness.refs, status: "blocked", blocked_reason: failed.join(",") }) }); return { eligible: false, reason: "Automatic reply blocked by safety gates.", failedGates: failed, decision, logId: row[0]?.id }; }
  const generatedText = (await getAIProvider().generateText({ purpose: "reply", maxTokens: 180, temperature: 0.1, prompt: `Write one concise, non-persuasive reply to this inbound message. Use only these verified business facts; if none, ask a clarifying question. Return only the reply. Verified facts:\n${readiness.context}\nInbound: ${JSON.stringify(input.message)}` })).trim(); const validation = validateText(generatedText, readiness, decision.intent); if (validation) { const row = await supabaseRequest<Array<{ id: string }>>("sales_auto_replies", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", conversation_id: input.conversationId || null, inbound_message_id: input.messageId || null, decision_mode: decision.mode, intent: decision.intent, confidence: decision.confidence, generated_text: generatedText, knowledge_refs: readiness.refs, status: "blocked", blocked_reason: validation }) }); return { eligible: false, reason: validation, failedGates: ["final_safety_validation"], decision, generatedText, logId: row[0]?.id }; }
  const dryRun = input.dryRun ?? settings.auto_reply_dry_run; const row = await supabaseRequest<Array<{ id: string }>>("sales_auto_replies", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", conversation_id: input.conversationId || null, inbound_message_id: input.messageId || null, decision_mode: decision.mode, intent: decision.intent, confidence: decision.confidence, generated_text: generatedText, knowledge_refs: readiness.refs, status: "eligible", blocked_reason: dryRun ? "dry_run_no_transport" : null, response_source: "auto_safe", dry_run: dryRun }) }); return { eligible: true, reason: dryRun ? "Eligible; dry-run prevented transport." : "Eligible for official transport.", failedGates: [], decision, generatedText, logId: row[0]?.id };
}
export async function listAutoReplies() { return supabaseRequest<unknown[]>(`sales_auto_replies?${scope}&select=*&order=created_at.desc&limit=50`); }
