import { getAIProvider, getAIProviderName } from "@/src/lib/ai/provider";
import { getLead, addLeadActivity } from "@/src/lib/leads/service";
import { supabaseRequest } from "@/src/lib/supabase/server";
import { decideReply } from "@/src/lib/reply-decision/service";
import { chooseReplyRecommendation } from "./strategy";
import type { Experiment, StrategyMetadata, Variant } from "./types";
import { getStylePromptContext } from "@/src/lib/personal-style/service";

type InboundMessage = { id: string; conversation_id: string; body: string; sent_at: string; direction: "inbound" | "outbound" };
type Lead = { id: string; business_name?: string | null; instagram_username: string; category?: string | null; description?: string | null; research_summary?: string | null; known_facts?: unknown };
const replySchema = { type: "object", additionalProperties: false, required: ["variants"], properties: { variants: { type: "array", minItems: 3, maxItems: 3, items: { type: "object", additionalProperties: false, required: ["variantKey", "message", "strategyMetadata"], properties: { variantKey: { type: "string", enum: ["A", "B", "C"] }, message: { type: "string" }, strategyMetadata: { type: "object", additionalProperties: false, required: ["replyIntent", "responseStrategy", "ctaType", "tone", "lengthClass", "personalizationType"], properties: { replyIntent: { type: "string" }, responseStrategy: { type: "string" }, ctaType: { type: "string" }, tone: { type: "string" }, lengthClass: { type: "string" }, personalizationType: { type: "string" } } } } } } } };
const fallback = (intent: string, facts: string, leadName: string) => {
  const verified = facts ? ` Based on what we have verified: ${facts}.` : " I can confirm the exact details once you share the relevant business information.";
  const base = intent === "asks_price" ? ["I can help with pricing. What type of business and enquiry volume should I price this for?", `Pricing depends on the setup and scope.${verified} Would you like to share a little more about your needs?`, `For ${leadName}, the right price depends on the workflow you want to improve. What would you like the solution to handle?`] : intent === "asks_more_info" ? ["Of course — I can share a concise overview of how it works. Which part would be most useful: lead capture, follow-up, or Instagram conversations?", `The service is designed to make sales conversations easier to manage.${verified} What would you like me to explain first?`, "Happy to send more details. Are you mainly interested in the workflow, the setup, or the expected use case?"] : ["Thanks for the question. I can explain the verified parts and clarify anything that is missing.", `I can share a concise overview${verified} What would you like to know first?`, "I want to make sure I give you an accurate answer. Which part should I focus on?"];
  return base.map((message, i) => ({ variantKey: ["A", "B", "C"][i], message, strategyMetadata: { replyIntent: intent, responseStrategy: ["direct_answer", "answer_plus_value", "qualification_first"][i], ctaType: i === 2 ? "question" : "soft_question", tone: i === 1 ? "direct" : "casual", lengthClass: "short", personalizationType: "business_context" } }));
};
function parse(raw: string, intent: string) { const parsed = JSON.parse(raw.replace(/^```json\s*|\s*```$/g, "")) as { variants?: Array<Record<string, unknown>> }; if (!Array.isArray(parsed.variants) || parsed.variants.length !== 3) throw new Error("AI reply experiment returned incomplete variants."); const variants = parsed.variants.map((value, i) => { const meta = value.strategyMetadata as Partial<StrategyMetadata> | undefined; const message = typeof value.message === "string" ? value.message.trim() : ""; if (!message || !meta?.replyIntent || !meta.responseStrategy || !meta.ctaType || !meta.tone || !meta.lengthClass || !meta.personalizationType) throw new Error("AI reply experiment returned incomplete variants."); return { variantKey: String(value.variantKey || ["A", "B", "C"][i]), message, strategyMetadata: { ...meta, replyIntent: meta.replyIntent || intent } as StrategyMetadata }; }); if (new Set(variants.map(v => v.strategyMetadata.responseStrategy)).size !== 3) throw new Error("AI reply experiment returned incomplete variants."); return variants; }
async function loadMessage(messageId: string) { const rows = await supabaseRequest<InboundMessage[]>(`sales_messages?id=eq.${encodeURIComponent(messageId)}&app_id=eq.sales_copilot&select=id,conversation_id,body,sent_at,direction`); if (!rows[0] || rows[0].direction !== "inbound") throw new Error("Inbound message not found."); return rows[0]; }
export async function generateReplyExperiment(messageId: string, leadId: string) {
  const message = await loadMessage(messageId); const lead = await getLead(leadId) as Lead | null; if (!lead) throw new Error("Lead not found.");
  const decision = await decideReply({ message: message.body, leadCategory: lead.category, messageId, leadId });
  if (decision.mode === "HUMAN_REQUIRED") return { decision, experiment: null, variants: [], recommendation: null };
  const existing = await supabaseRequest<Experiment[]>(`sales_ai_experiments?app_id=eq.sales_copilot&experiment_type=eq.reply&inbound_message_id=eq.${encodeURIComponent(messageId)}&select=*&order=created_at.desc`); if (existing[0]) { const variants = await supabaseRequest<Variant[]>(`sales_ai_message_variants?app_id=eq.sales_copilot&experiment_id=eq.${encodeURIComponent(existing[0].id)}&select=*`); return { decision, experiment: { ...existing[0], variants }, variants, recommendation: variants.find(v => v.id === existing[0].recommended_variant_id) || variants[0] || null }; }
  const facts = [lead.description, lead.research_summary, Array.isArray(lead.known_facts) ? lead.known_facts.join("; ") : ""].filter(Boolean).join("; ").slice(0, 500); const styleContext = await getStylePromptContext(); const prompt = [`Generate exactly three meaningfully different user-editable reply strategies for this inbound message. Intent: ${decision.intent}. Do not invent prices, discounts, terms, timelines, capabilities, policies, guarantees, or commitments. If facts are missing, ask a concise clarifying question. Return only JSON.`, `Lead: ${JSON.stringify({ business_name: lead.business_name, instagram_username: lead.instagram_username, category: lead.category })}. Verified facts: ${JSON.stringify(facts)}. Inbound message: ${JSON.stringify(message.body)}`, styleContext].filter(Boolean).join("\n");
  let generated: ReturnType<typeof fallback>; try { generated = parse(await getAIProvider().generateText({ purpose: "reply", maxTokens: 900, temperature: 0.2, responseFormat: { type: "json_schema", json_schema: { name: "sales_reply_experiment", strict: true, schema: replySchema } }, prompt }), decision.intent) as ReturnType<typeof fallback>; } catch (error) { if (getAIProviderName() !== "Mock" && !(error instanceof Error && error.message.includes("incomplete variants"))) throw error; generated = fallback(decision.intent, facts, String(lead.business_name || lead.instagram_username)); }
  const experiment = (await supabaseRequest<Experiment[]>("sales_ai_experiments", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", lead_id: leadId, objective: `Reply strategies for ${decision.intent}`, experiment_type: "reply", inbound_message_id: messageId, conversation_id: message.conversation_id, status: "active" }) }))[0]; if (!experiment) throw new Error("Reply experiment could not be created.");
  const variants = await supabaseRequest<Variant[]>("sales_ai_message_variants", { method: "POST", body: JSON.stringify(generated.map(v => ({ app_id: "sales_copilot", experiment_id: experiment.id, variant_key: v.variantKey, message: v.message, strategy_metadata: v.strategyMetadata }))) }); const recommendation = chooseReplyRecommendation(variants, new Map()); await supabaseRequest(`sales_ai_experiments?id=eq.${encodeURIComponent(experiment.id)}&app_id=eq.sales_copilot`, { method: "PATCH", body: JSON.stringify({ recommended_variant_id: recommendation?.id || null }) }); await addLeadActivity(leadId, "ai_reply_experiment_generated", "Generated reply strategies for review.", { experiment_id: experiment.id, inbound_message_id: messageId, decision_mode: decision.mode }); return { decision, experiment: { ...experiment, variants, recommended_variant_id: recommendation?.id || null }, variants, recommendation };
}
