import { getAIProvider, getAIProviderName } from "@/src/lib/ai/provider";
import { getLead, addLeadActivity } from "@/src/lib/leads/service";
import { supabaseRequest } from "@/src/lib/supabase/server";
import { chooseRecommendation } from "./strategy";
import { MINIMUM_SAMPLE_SIZE, outcomeScore, safeRate } from "./scoring";
import { OUTCOME_TYPES, type Experiment, type Outcome, type OutcomeType, type StrategyMetadata, type Variant } from "./types";

const scope = "app_id=eq.sales_copilot";
const variantSchema = { type: "object", additionalProperties: false, required: ["variants"], properties: { variants: { type: "array", minItems: 3, maxItems: 3, items: { type: "object", additionalProperties: false, required: ["variantKey", "message", "strategyMetadata"], properties: { variantKey: { type: "string", enum: ["A", "B", "C"] }, message: { type: "string" }, strategyMetadata: { type: "object", additionalProperties: false, required: ["openerType", "ctaType", "tone", "personalizationType", "lengthClass"], properties: { openerType: { type: "string" }, ctaType: { type: "string" }, tone: { type: "string" }, personalizationType: { type: "string" }, lengthClass: { type: "string" } } } } } } } };
function parseVariants(raw: string) { const parsed = JSON.parse(raw.replace(/^```json\s*|\s*```$/g, "")) as { variants?: Array<Record<string, unknown>> }; const variants = parsed.variants; if (!Array.isArray(variants) || variants.length !== 3) throw new Error("AI experiment returned incomplete structured variants."); return variants.map((variant) => { const metadata = (variant.strategyMetadata || variant.strategy_metadata) as Partial<StrategyMetadata> | undefined; const variantKey = String(variant.variantKey || variant.variant_key || ""); const message = typeof variant.message === "string" ? variant.message.trim() : ""; if (!variantKey || !message || !metadata?.openerType || !metadata.ctaType || !metadata.tone || !metadata.personalizationType || !metadata.lengthClass) throw new Error("AI experiment returned incomplete structured variants."); return { variantKey, message, strategyMetadata: metadata as StrategyMetadata }; }); }
function fallbackVariants(lead: Record<string, unknown>) { const name = String(lead.business_name || lead.instagram_username || "your business"); const facts = String(lead.research_summary || lead.description || "").slice(0, 180); return [{ variantKey: "A", message: `I was curious about how ${name} handles Instagram enquiries${facts ? ` around ${facts}` : ""}. Is that something you actively focus on?`, strategyMetadata: { openerType: "curiosity", ctaType: "question", tone: "casual", personalizationType: "business_specific", lengthClass: "short" } }, { variantKey: "B", message: `Hi ${name}, we help businesses make Instagram conversations easier to turn into qualified enquiries. Would a quick example be useful?`, strategyMetadata: { openerType: "direct_benefit", ctaType: "soft_offer", tone: "direct", personalizationType: "business_specific", lengthClass: "short" } }, { variantKey: "C", message: `Quick question for ${name}: are Instagram enquiries currently easy for you to manage?`, strategyMetadata: { openerType: "short_question", ctaType: "question", tone: "casual", personalizationType: "business_specific", lengthClass: "short" } }]; }
async function performanceRows() { const variants = await supabaseRequest<Variant[]>(`sales_ai_message_variants?select=*&${scope}`); const outcomes = await supabaseRequest<Outcome[]>(`sales_ai_outcomes?select=*&${scope}`); return { variants, outcomes }; }
export async function generateExperiment(leadId: string): Promise<{ experiment: Experiment; variants: Variant[]; recommendation: Variant }> {
  const lead = await getLead(leadId); if (!lead) throw new Error("Lead not found.");
  const { variants: priorVariants, outcomes } = await performanceRows();
  const priorByOpener = new Map<string, { sentCount: number; replies: number }>();
  for (const variant of priorVariants) { const key = variant.strategy_metadata?.openerType; if (!key) continue; const current = priorByOpener.get(key) || { sentCount: 0, replies: 0 }; const variantOutcomes = outcomes.filter(o => o.variant_id === variant.id); current.sentCount += variant.sent ? 1 : 0; if (variantOutcomes.some(o => ["reply_neutral", "reply_positive", "asks_price", "asks_demo", "asks_more_info", "meeting_booked", "converted"].includes(o.outcome_type))) current.replies += 1; priorByOpener.set(key, current); }
  const performanceContext = [...priorByOpener.entries()].map(([opener, stats]) => `${opener}: ${stats.sentCount} sent, ${stats.replies} replies`).join("; ") || "No meaningful historical data yet.";
  const prompt = [`Generate exactly three genuinely different concise Instagram outreach variants for this lead. Use opener strategies curiosity, direct_benefit, and short_question, one each. Return only JSON matching the schema.`, `Store strategy metadata at generation time; do not infer it later. Do not invent facts. Use only the supplied lead and research data. Historical performance is observed correlation only and must never override factual context.`, `Observed performance for similar recorded variants: ${performanceContext}`, `Lead: ${JSON.stringify({ business_name: lead.business_name, instagram_username: lead.instagram_username, category: lead.category, description: lead.description, website: lead.website, research_summary: lead.research_summary, known_facts: lead.known_facts, enrichment: lead.enrichment })}`].join("\n");
  let generated: ReturnType<typeof fallbackVariants>; try { generated = parseVariants(await getAIProvider().generateText({ prompt, purpose: "experiment", maxTokens: 900, temperature: 0.2, responseFormat: { type: "json_schema", json_schema: { name: "sales_outreach_experiment", strict: true, schema: variantSchema } } })) as ReturnType<typeof fallbackVariants>; } catch (error) { if (getAIProviderName() !== "Mock" && !(error instanceof Error && error.message.includes("incomplete structured variants"))) throw error; generated = fallbackVariants(lead); }
  const experimentRows = await supabaseRequest<Experiment[]>("sales_ai_experiments", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", lead_id: leadId, objective: "Compare outreach strategies", status: "active" }) }); const experiment = experimentRows[0]; if (!experiment) throw new Error("Experiment could not be created.");
  const saved = await supabaseRequest<Variant[]>("sales_ai_message_variants", { method: "POST", body: JSON.stringify(generated.map(v => ({ app_id: "sales_copilot", experiment_id: experiment.id, variant_key: v.variantKey, message: v.message, strategy_metadata: v.strategyMetadata }))) });
  const recommendation = chooseRecommendation(saved, new Map([...priorByOpener.entries()].map(([key, value]) => [key, { sentCount: value.sentCount, replyCount: value.replies, score: 0, replyRate: safeRate(value.replies, value.sentCount), meaningful: value.sentCount >= MINIMUM_SAMPLE_SIZE }]))); if (!recommendation) throw new Error("Experiment recommendation could not be selected.");
  const updated = (await supabaseRequest<Experiment[]>(`sales_ai_experiments?id=eq.${experiment.id}&${scope}`, { method: "PATCH", body: JSON.stringify({ recommended_variant_id: recommendation.id }) }))[0]; await addLeadActivity(leadId, "ai_experiment_generated", "Generated three outreach variants.", { experiment_id: experiment.id, recommended_variant_id: recommendation.id }); return { experiment: { ...updated, variants: saved }, variants: saved, recommendation };
}
export async function markVariantSent(variantId: string, selected = true) { const rows = await supabaseRequest<Variant[]>(`sales_ai_message_variants?id=eq.${encodeURIComponent(variantId)}&${scope}`, { method: "PATCH", body: JSON.stringify({ sent: true, sent_at: new Date().toISOString(), selected }) }); const variant = rows[0]; if (!variant) throw new Error("Variant not found."); if (selected) { await supabaseRequest(`sales_ai_message_variants?experiment_id=eq.${encodeURIComponent(variant.experiment_id)}&${scope}`, { method: "PATCH", body: JSON.stringify({ selected: false }) }); await supabaseRequest(`sales_ai_message_variants?id=eq.${encodeURIComponent(variantId)}&${scope}`, { method: "PATCH", body: JSON.stringify({ selected: true }) }); await supabaseRequest(`sales_ai_experiments?id=eq.${encodeURIComponent(variant.experiment_id)}&${scope}`, { method: "PATCH", body: JSON.stringify({ selected_variant_id: variantId }) }); } return variant; }
export async function selectVariant(variantId: string) { const rows = await supabaseRequest<Variant[]>(`sales_ai_message_variants?id=eq.${encodeURIComponent(variantId)}&${scope}`, { method: "PATCH", body: JSON.stringify({ selected: true }) }); const variant = rows[0]; if (!variant) throw new Error("Variant not found."); await supabaseRequest(`sales_ai_message_variants?experiment_id=eq.${encodeURIComponent(variant.experiment_id)}&id=neq.${encodeURIComponent(variantId)}&${scope}`, { method: "PATCH", body: JSON.stringify({ selected: false }) }); await supabaseRequest(`sales_ai_experiments?id=eq.${encodeURIComponent(variant.experiment_id)}&${scope}`, { method: "PATCH", body: JSON.stringify({ selected_variant_id: variantId }) }); return variant; }
export async function recordOutcome(variantId: string, outcomeType: OutcomeType, source = "manual", metadata: Record<string, unknown> = {}, idempotencyKey = `${variantId}:${outcomeType}`) { if (!OUTCOME_TYPES.includes(outcomeType)) throw new Error("Unsupported outcome type."); const existing = await supabaseRequest<Outcome[]>(`sales_ai_outcomes?variant_id=eq.${encodeURIComponent(variantId)}&idempotency_key=eq.${encodeURIComponent(idempotencyKey)}&${scope}`); if (existing[0]) return { outcome: existing[0], duplicate: true }; const rows = await supabaseRequest<Outcome[]>("sales_ai_outcomes", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", variant_id: variantId, outcome_type: outcomeType, source, metadata, idempotency_key: idempotencyKey }) }); if (!rows[0]) throw new Error("Outcome could not be recorded."); return { outcome: rows[0], duplicate: false }; }
export async function removeOutcome(variantId: string, outcomeId: string) { const rows = await supabaseRequest<Outcome[]>(`sales_ai_outcomes?id=eq.${encodeURIComponent(outcomeId)}&variant_id=eq.${encodeURIComponent(variantId)}&${scope}`, { method: "DELETE" }); if (!rows[0]) throw new Error("Outcome not found."); return rows[0]; }
export async function getPerformance(filters: { category?: string; platform?: string; openerType?: string } = {}) { const { variants, outcomes } = await performanceRows(); const experiments = await supabaseRequest<Experiment[]>(`sales_ai_experiments?select=*&${scope}`); const leads = await supabaseRequest<Record<string, unknown>[]>(`sales_leads?select=id,category,instagram_username&${scope}`); const leadById = new Map(leads.map(l => [String(l.id), l])); const experimentById = new Map(experiments.map(e => [e.id, e])); const groups = new Map<string, { dimension: string; niche: string | null; platform: string | null; sentCount: number; replyCount: number; positiveReplyCount: number; meetingCount: number; conversionCount: number; score: number }>(); for (const variant of variants) { if (!variant.sent) continue; const experiment = experimentById.get(variant.experiment_id); const lead = experiment ? leadById.get(experiment.lead_id) : undefined; const metadata = variant.strategy_metadata || {} as StrategyMetadata; const niche = lead?.category ? String(lead.category) : null; const platform = "instagram"; if (filters.category && niche?.toLowerCase() !== filters.category.toLowerCase()) continue; if (filters.platform && platform !== filters.platform) continue; if (filters.openerType && metadata.openerType !== filters.openerType) continue; const key = `${metadata.openerType}|${niche || "global"}|${platform}`; const group = groups.get(key) || { dimension: metadata.openerType, niche, platform, sentCount: 0, replyCount: 0, positiveReplyCount: 0, meetingCount: 0, conversionCount: 0, score: 0 }; group.sentCount++; const variantOutcomes = outcomes.filter(o => o.variant_id === variant.id); if (variantOutcomes.some(o => ["reply_neutral", "reply_positive", "asks_price", "asks_demo", "asks_more_info", "meeting_booked", "converted"].includes(o.outcome_type))) group.replyCount++; if (variantOutcomes.some(o => ["reply_positive", "asks_price", "asks_demo", "asks_more_info", "meeting_booked", "converted"].includes(o.outcome_type))) group.positiveReplyCount++; for (const outcome of variantOutcomes) { group.score += outcomeScore(outcome.outcome_type); if (outcome.outcome_type === "meeting_booked") group.meetingCount++; if (outcome.outcome_type === "converted") group.conversionCount++; } groups.set(key, group); } return [...groups.values()].map(group => ({ ...group, replyRate: safeRate(group.replyCount, group.sentCount), positiveReplyRate: safeRate(group.positiveReplyCount, group.sentCount), meetingRate: safeRate(group.meetingCount, group.sentCount), conversionRate: safeRate(group.conversionCount, group.sentCount), meaningful: group.sentCount >= MINIMUM_SAMPLE_SIZE, label: group.sentCount >= MINIMUM_SAMPLE_SIZE ? "observed performance" : "insufficient data" })); }
