"use client";
import { useEffect, useState } from "react";
type Item = { id: string; category: string; key: string; title: string; value: unknown; status: string };
export default function BusinessKnowledgePanel() {
  const [items, setItems] = useState<Item[]>([]); const [form, setForm] = useState({ category: "pricing", key: "", title: "", value: "", status: "UNVERIFIED" }); const [error, setError] = useState("");
  const load = () => { void fetch("/api/business-knowledge").then(r => r.json() as Promise<Item[]>).then(setItems).catch(() => setError("Неуспешно зареждане на бизнес знанията.")); }; useEffect(() => { load(); }, []);
  const save = async () => { setError(""); try { const value = JSON.parse(form.value); const response = await fetch("/api/business-knowledge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, value }) }); if (!response.ok) { const body = await response.json() as { error?: string }; throw new Error(body.error || "Неуспешно записване."); } setForm({ ...form, key: "", title: "", value: "" }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Неуспешно записване."); } };
  return <section className="content"><h2>Бизнес знания и правила</h2><p className="muted">Само VERIFIED факти се използват от AI. Автоматичното изпращане остава изключено.</p><div className="form-grid"><label>Категория<input value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}/></label><label>Ключ<input value={form.key} onChange={e => setForm({ ...form, key: e.target.value })}/></label><label>Заглавие<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/></label><label>Статус<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option>UNVERIFIED</option><option>VERIFIED</option><option>DISABLED</option></select></label><label>Стойност (JSON)<textarea value={form.value} onChange={e => setForm({ ...form, value: e.target.value })}/></label></div>{error && <p className="form-error">{error}</p>}<button className="primary" onClick={() => void save()}>Добави знание</button><div className="table-card">{items.map(item => <div className="table-row" key={item.id}><span>{item.category}.{item.key}</span><span>{item.title}</span><span className="muted">{item.status}</span></div>)}</div></section>;
}
