"use client";
import { useState } from "react";
import { ArrowRight, Camera, Check, ExternalLink, Globe2, LoaderCircle, MapPin, Search, Sparkles } from "lucide-react";
import { EmptyState, SectionHeader } from "./workspace-ui";

type Profile = { url?: string; username?: string; verified: boolean; sourceUrl?: string };
type Candidate = { id: string; business_name: string; platform: string | null; username: string | null; profile_url: string | null; website: string | null; location: string | null; category: string | null; short_description: string | null; why_relevant: string | null; source_urls: string[]; confidence: number | null; enrichment?: Record<string, Profile> | null };
type ChatMessage = { role: "user" | "assistant"; content: string };
const examples = ["Find 5 car detailing businesses in Sofia with a public Instagram presence.", "Find independent bakeries in Plovdiv with a website or Instagram profile.", "Find small beauty salons in Varna with public contact channels."];
const stages = ["Searching public web", "Validating sources", "Deduplicating candidates", "Preparing results"];
const channels = ["website", "instagram", "tiktok", "facebook", "youtube", "linkedin", "x"];
async function readJson(response: Response) { const value = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(value.error || "Request failed.")); return value; }
const validUrl = (value?: string | null) => value && /^https?:\/\//i.test(value) ? value : null;
function channelLinks(candidate: Candidate) { return channels.flatMap(name => { const profile = candidate.enrichment?.[name]; if (profile?.verified && validUrl(profile.url) && validUrl(profile.sourceUrl)) return [{ name, url: profile.url! }]; if (name === "website" && validUrl(candidate.website)) return [{ name, url: candidate.website! }]; if (name === "instagram" && validUrl(candidate.profile_url)) return [{ name, url: candidate.profile_url! }]; return []; }); }
export default function LeadFinderPanel() {
  const [query, setQuery] = useState(""); const [lastQuery, setLastQuery] = useState(""); const [sessionId, setSessionId] = useState(""); const [messages, setMessages] = useState<ChatMessage[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [selected, setSelected] = useState<string[]>([]); const [inspected, setInspected] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [partial, setPartial] = useState("");
  const inspectedCandidate = candidates.find(candidate => candidate.id === inspected);
  const selectable = candidates.filter(candidate => candidate.username || candidate.enrichment?.instagram?.verified && candidate.enrichment.instagram.username);
  async function search(event?: React.FormEvent) { event?.preventDefault(); const request = query.trim(); if (!request || loading) return; setLoading(true); setLastQuery(request); setError(""); setNotice(""); setPartial(""); try { const data = await readJson(await fetch("/api/lead-finder/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query: request, sessionId: sessionId || undefined }) })); setSessionId(String(data.sessionId)); setMessages(current => [...current, { role: "user", content: request }, { role: "assistant", content: String(data.answer || "") }]); const found = data.candidates as Candidate[]; setCandidates(current => sessionId ? [...current, ...found.filter(item => !current.some(previous => previous.id === item.id))] : found); setSelected([]); if (found[0]) setInspected(found[0].id); const requested = Number(request.match(/\b(?:find|give|show)\s+(?:me\s+)?(\d+)\b/i)?.[1]); if (requested > 0 && found.length < requested) setPartial(`Found ${found.length} new sourced ${found.length === 1 ? "candidate" : "candidates"} of ${requested} requested. The remaining results were not verified.`); setQuery(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to search."); } finally { setLoading(false); } }
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); }
  async function add(candidate: Candidate, research = false) { setBusy(candidate.id); setError(""); setNotice(""); try { const data = await readJson(await fetch(`/api/lead-finder/candidates/${candidate.id}/add`, { method: "POST" })); if (data.duplicate) setNotice(`${candidate.business_name} already exists as a lead.`); else { setNotice(`${candidate.business_name} added as a lead.`); if (research) { const lead = data.lead as Record<string, unknown>; await readJson(await fetch("/api/ai/research", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: lead.id }) })); setNotice(`${candidate.business_name} added and researched.`); } } } catch (e) { setError(e instanceof Error ? e.message : "Unable to add candidate."); } finally { setBusy(""); } }
  async function addSelected() { for (const id of selected) { const candidate = candidates.find(item => item.id === id); if (candidate) await add(candidate); } }
  async function enrich(candidate: Candidate) { setBusy(candidate.id); setError(""); try { const data = await readJson(await fetch(`/api/lead-finder/candidates/${candidate.id}/enrich`, { method: "POST" })); setCandidates(current => current.map(item => item.id === candidate.id ? data.candidate as Candidate : item)); setNotice(`${candidate.business_name} profiles checked against public sources.`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to verify profiles."); } finally { setBusy(""); } }
  return <div className="content lead-finder"><div className="finder-title-row"><SectionHeader eyebrow="PUBLIC WEB DISCOVERY" title="Lead Finder" description="Find businesses from public sources, then review the evidence before adding them." />{sessionId && <button className="secondary" onClick={() => { setSessionId(""); setMessages([]); setCandidates([]); setSelected([]); setInspected(null); setPartial(""); setError(""); }}>New session</button>}</div>
    {!sessionId && !loading && <section className="finder-intro"><div className="finder-intro-icon"><Search size={23}/></div><h3>Find your next conversation</h3><p>Describe a niche, location, and public presence. Search results stay grounded in source links you can inspect.</p><div className="finder-examples"><span className="overline">TRY A SEARCH</span>{examples.map(example => <button key={example} className="example-query" onClick={() => setQuery(example)}>{example}<ArrowRight size={15}/></button>)}</div></section>}
    <div className={`finder-workspace ${sessionId ? "has-results" : ""}`}><div className="finder-main">
      {messages.length > 0 && <section className="finder-history" aria-label="Search conversation"><div className="panel-heading"><span className="overline">CONVERSATION</span><span className="muted">Session active</span></div>{messages.map((message, index) => <div className={`finder-message ${message.role}`} key={`${message.role}-${index}`}><b>{message.role === "user" ? "You" : "Lead Finder"}</b><p>{message.content}</p></div>)}</section>}
      <form onSubmit={search} className="finder-input"><label className="overline" htmlFor="finder-query">{sessionId ? "REFINE OR CONTINUE SEARCH" : "DESCRIBE THE BUSINESSES TO FIND"}</label><textarea id="finder-query" value={query} onChange={event => setQuery(event.target.value)} placeholder={sessionId ? "Ask a follow-up, such as ‘Find 5 more without repeats’…" : "Find businesses by niche, place, platform, or criteria…"} rows={3} disabled={loading}/><div className="finder-input-footer"><span>Public web sources · Manual review</span><button className="primary" disabled={loading || !query.trim()}>{loading ? <><LoaderCircle size={15} className="spin"/> Searching…</> : <><Search size={15}/> {sessionId ? "Continue search" : "Find leads"}</>}</button></div></form>
      {loading && <div className="finder-progress" role="status" aria-live="polite"><div className="panel-heading"><b>Searching public sources</b><LoaderCircle size={16} className="spin"/></div><p>Results will appear after verification. Existing results remain available.</p><ol>{stages.map(stage => <li key={stage}><span className="stage-dot"/>{stage}</li>)}</ol></div>}
      {error && <div className="form-error finder-alert" role="alert"><span>{error}</span><button className="secondary" onClick={() => { setQuery(lastQuery); setError(""); }} type="button">Retry query</button></div>}
      {notice && <p className="finder-notice" role="status"><Check size={15}/>{notice}</p>}
      {partial && !loading && <div className="finder-partial" role="status"><div><b>Partial results</b><p>{partial}</p></div></div>}
      {sessionId && !loading && candidates.length === 0 && !partial && <div className="finder-partial"><div><b>No new candidates verified in this search</b><p>Try broader criteria or continue the conversation. We will not fill the list with unsourced businesses.</p></div></div>}
      {candidates.length > 0 && <section className="finder-results"><div className="finder-results-head"><div><span className="overline">SEARCH RESULTS</span><h3>{candidates.length} {candidates.length === 1 ? "candidate" : "candidates"}</h3></div><div className="finder-bulk"><button className="secondary" type="button" onClick={() => setSelected(selected.length === selectable.length ? [] : selectable.map(candidate => candidate.id))}>{selected.length === selectable.length && selectable.length ? "Clear selection" : "Select all eligible"}</button><button className="primary" type="button" disabled={loading || !!busy || !selected.length} onClick={() => void addSelected()}>Add selected ({selected.length})</button></div></div><div className="finder-list">{candidates.map(candidate => { const links = channelLinks(candidate); const eligible = selectable.some(item => item.id === candidate.id); return <article className={`finder-card ${inspected === candidate.id ? "is-inspected" : ""}`} key={candidate.id}><input type="checkbox" aria-label={`Select ${candidate.business_name}`} checked={selected.includes(candidate.id)} onChange={() => toggle(candidate.id)} disabled={!eligible || !!busy}/><div className="finder-card-main"><button className="finder-card-title" type="button" onClick={() => setInspected(candidate.id)} aria-pressed={inspected === candidate.id}><span>{candidate.business_name}</span><ArrowRight size={14}/></button><div className="finder-meta">{candidate.category && <span>{candidate.category}</span>}{candidate.location && <span><MapPin size={12}/>{candidate.location}</span>}{candidate.confidence != null && <span className="confidence">Confidence {Math.round(candidate.confidence * 100)}%</span>}</div>{candidate.short_description && <p>{candidate.short_description}</p>}{candidate.why_relevant && <p className="finder-why"><b>Why relevant</b> {candidate.why_relevant}</p>}<div className="finder-channels">{links.map(link => <a key={link.name} href={link.url} target="_blank" rel="noreferrer" title={link.url}>{link.name === "instagram" ? <Camera size={13}/> : <Globe2 size={13}/>} {link.name}<ExternalLink size={11}/></a>)}{candidate.source_urls[0] && validUrl(candidate.source_urls[0]) && <a href={candidate.source_urls[0]} target="_blank" rel="noreferrer">Source <ExternalLink size={11}/></a>}</div></div><div className="finder-card-actions"><button className="secondary" type="button" onClick={() => setInspected(candidate.id)}>Details</button><button className="secondary" type="button" disabled={!!busy || !eligible} onClick={() => void add(candidate)}>Add lead</button><button className="primary" type="button" disabled={!!busy || !eligible} onClick={() => void add(candidate, true)}>Add & Research</button></div></article>; })}</div></section>}
    </div>{sessionId && <aside className="finder-inspector" aria-label="Candidate inspector">{inspectedCandidate ? <><div className="inspector-top"><span className="overline">CANDIDATE INSPECTOR</span><h3>{inspectedCandidate.business_name}</h3><p>{[inspectedCandidate.category, inspectedCandidate.location].filter(Boolean).join(" · ") || "Business candidate"}</p></div><div className="inspector-actions"><button className="secondary" disabled={!!busy} onClick={() => void enrich(inspectedCandidate)}><Sparkles size={14}/>{busy === inspectedCandidate.id ? "Checking…" : "Verify channels"}</button><button className="primary" disabled={!!busy || !selectable.some(item => item.id === inspectedCandidate.id)} onClick={() => void add(inspectedCandidate, true)}>Add & Research</button></div><InspectorSection title="Overview">{inspectedCandidate.short_description || "No description available from this search."}</InspectorSection><div className="inspector-section"><h4>Public channels & profiles</h4>{channelLinks(inspectedCandidate).length ? <div className="inspector-links">{channelLinks(inspectedCandidate).map(link => <a href={link.url} target="_blank" rel="noreferrer" key={link.name}><span>{link.name}{inspectedCandidate.enrichment?.[link.name]?.verified ? " · verified" : ""}</span><ExternalLink size={14}/></a>)}</div> : <p>No channel profiles available yet. Review sources or verify channels.</p>}</div><InspectorSection title="Research summary">{inspectedCandidate.short_description || "Research becomes available after Add & Research."}</InspectorSection><InspectorSection title="Known facts" note="SOURCE-BASED">{inspectedCandidate.source_urls.length ? "Review the public source links below. No separate fact list is available for this candidate." : "No facts recorded yet."}</InspectorSection><InspectorSection title="Inferences" note="NOT VERIFIED">No inferences recorded for this candidate.</InspectorSection><InspectorSection title="Why relevant">{inspectedCandidate.why_relevant || "No relevance note available."}</InspectorSection><InspectorSection title="Outreach angle">Available after adding and researching the lead.</InspectorSection><div className="inspector-section"><h4>Sources</h4><div className="inspector-links">{inspectedCandidate.source_urls.filter(url => validUrl(url)).map((url, index) => <a href={url} target="_blank" rel="noreferrer" key={url}><span>Public source {index + 1}</span><ExternalLink size={14}/></a>)}</div></div></> : <EmptyState icon={Search} title="Select a candidate" description="Choose a result to review its public profiles, context, and source links."/>}</aside>}</div>
  </div>;
}
function InspectorSection({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) { return <section className="inspector-section"><h4>{title}{note && <span className="inspector-note">{note}</span>}</h4><p>{children}</p></section>; }
