"use client";
import { useState } from "react";

type Candidate = { id: string; business_name: string; platform: string | null; username: string | null; profile_url: string | null; website: string | null; location: string | null; category: string | null; short_description: string | null; why_relevant: string | null; public_contact_method: string | null; source_urls: string[]; confidence: number | null };
type ChatMessage = { role: "user" | "assistant"; content: string };
async function readJson(response: Response) { const value = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(value.error || "Request failed.")); return value; }
export default function LeadFinderPanel() {
  const [query, setQuery] = useState(""); const [sessionId, setSessionId] = useState(""); const [messages, setMessages] = useState<ChatMessage[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function search(event?: React.FormEvent) { event?.preventDefault(); if (!query.trim() || loading) return; setLoading(true); setError(""); setNotice(""); try { const data = await readJson(await fetch("/api/lead-finder/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query, sessionId: sessionId || undefined }) })); setSessionId(String(data.sessionId)); setMessages(current => [...current, { role: "user", content: query }, { role: "assistant", content: String(data.answer || "") }]); setCandidates(data.candidates as Candidate[]); setSelected([]); setQuery(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to search."); } finally { setLoading(false); } }
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); }
  async function add(candidate: Candidate, research = false) { setBusy(candidate.id); setError(""); setNotice(""); try { const data = await readJson(await fetch(`/api/lead-finder/candidates/${candidate.id}/add`, { method: "POST" })); if (data.duplicate) setNotice(`${candidate.business_name} already exists as a lead.`); else { setNotice(`${candidate.business_name} added as a lead.`); if (research) { const lead = data.lead as Record<string, unknown>; await readJson(await fetch("/api/ai/research", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: lead.id }) })); setNotice(`${candidate.business_name} added and researched.`); } } } catch (e) { setError(e instanceof Error ? e.message : "Unable to add candidate."); } finally { setBusy(""); } }
  async function addSelected() { for (const id of selected) { const candidate = candidates.find(item => item.id === id); if (candidate?.username) await add(candidate); } }
  return <div className="content lead-finder"><div className="section-heading"><div><h2>Lead Finder</h2><p>Describe the businesses you want to find. Results use public web sources.</p></div>{sessionId && <span className="muted">Conversational search active</span>}</div><div className="finder-chat">{messages.length === 0 ? <p className="muted">Try: “Find 5 cake businesses in Sofia with a public Instagram or website presence.”</p> : messages.map((message, index) => <div className={`finder-message ${message.role}`} key={`${message.role}-${index}`}><b>{message.role === "user" ? "You" : "Lead Finder"}</b><p>{message.content}</p></div>)}<form onSubmit={search} className="finder-input"><textarea value={query} onChange={event => setQuery(event.target.value)} placeholder="Find businesses by niche, place, platform, or criteria…" rows={3}/><button className="primary" disabled={loading || !query.trim()}>{loading ? "Searching…" : "Search the web"}</button></form></div>{error && <div className="form-error" role="alert">{error}</div>}{notice && <p className="finder-notice">{notice}</p>}{candidates.length > 0 && <section className="finder-results"><div className="section-heading"><div><h3>Candidates <span>{candidates.length}</span></h3><p>Select verified candidates to add to your leads.</p></div><div className="finder-bulk"><button className="secondary" onClick={() => setSelected(candidates.filter(candidate => candidate.username).map(candidate => candidate.id))}>Select All</button><button className="primary" disabled={loading || !!busy || !selected.length} onClick={() => void addSelected()}>Add Selected Leads</button></div></div>{candidates.map(candidate => <article className="finder-card" key={candidate.id}><input type="checkbox" checked={selected.includes(candidate.id)} onChange={() => toggle(candidate.id)} disabled={!candidate.username || !!busy}/><div className="finder-card-main"><h4>{candidate.business_name}</h4><p>{[candidate.platform, candidate.username ? `@${candidate.username}` : "No verified username", candidate.location, candidate.category].filter(Boolean).join(" · ")}</p><p>{candidate.short_description || "No description supplied."}</p>{candidate.why_relevant && <p><b>Why relevant:</b> {candidate.why_relevant}</p>}<p><b>Confidence:</b> {candidate.confidence == null ? "—" : `${Math.round(candidate.confidence * 100)}%`} · <b>Sources:</b> {candidate.source_urls.map(url => <a href={url} target="_blank" rel="noreferrer" key={url}>View source</a>)}</p></div><div className="finder-card-actions"><button className="secondary" disabled={!!busy || !candidate.username} onClick={() => void add(candidate)}>Add Lead</button><button className="secondary" disabled={!!busy || !candidate.username} onClick={() => void add(candidate, true)}>Add & Research</button></div></article>)}</section>}</div>;
}
