"use client";
import { useEffect, useState } from "react";
import { Check, Sparkles } from "lucide-react";

type Variant = { id: string; variant_key: string; message: string; strategy_metadata: { openerType?: string; responseStrategy?: string; ctaType: string; tone: string; personalizationType: string; lengthClass: string }; selected: boolean; sent: boolean };
type Experiment = { id: string; recommended_variant_id: string | null; selected_variant_id: string | null };
type Performance = { meaningful: boolean };
type Suggestion = { id: string; suggested_outcomes: Array<{ outcome: string; confidence: number }>; };
type ReplyDecision = { mode: "AUTO_SAFE" | "SUGGEST_ONLY" | "HUMAN_REQUIRED"; intent: string; reason: string };
type StyleProfile = { status: string; sample_count: number; profile: { preferredTone: string; preferredLength: string; greetingStyle: string; emojiUsage: string } };
const outcomes = ["no_reply", "reply_neutral", "reply_positive", "reply_negative", "not_interested", "asks_price", "asks_demo", "asks_more_info", "meeting_booked", "converted", "blocked"];
const outcomeLabel: Record<string, string> = { reply_positive: "Положителен Reply", asks_price: "Пита за цена", asks_demo: "Иска Demo", asks_more_info: "Иска повече информация", not_interested: "Не е заинтересован" };
async function json(response: Response) { const body = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(body.error || "Заявката не успя.")); return body; }

export default function LearningPanel({ leadId }: { leadId: string }) {
  const [experiment, setExperiment] = useState<Experiment | null>(null); const [variants, setVariants] = useState<Variant[]>([]); const [chosen, setChosen] = useState(""); const [outcome, setOutcome] = useState(""); const [suggestions, setSuggestions] = useState<Suggestion[]>([]); const [inboundText, setInboundText] = useState(""); const [replyDecision, setReplyDecision] = useState<ReplyDecision | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [performance, setPerformance] = useState<Performance[]>([]); const [style, setStyle] = useState<StyleProfile | null>(null);
  function refreshSuggestions() { fetch(`/api/ai/outcome-suggestions?leadId=${encodeURIComponent(leadId)}`).then(json).then(data => setSuggestions(data.suggestions as Suggestion[])).catch(() => setSuggestions([])); }
  useEffect(() => { setExperiment(null); setVariants([]); setChosen(""); setOutcome(""); setNotice(""); refreshSuggestions(); fetch("/api/ai/performance").then(json).then(data => setPerformance(data.performance as Performance[])).catch(() => setPerformance([])); fetch("/api/ai/style-profile").then(json).then(data => setStyle(data as unknown as StyleProfile)).catch(() => setStyle(null)); }, [leadId]);
  async function run(action: () => Promise<void>) { setBusy(true); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : "Неуспешно обновяване."); } finally { setBusy(false); } }
  function generate() { void run(async () => { const data = await json(await fetch("/api/ai/experiments/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId }) })); setExperiment(data.experiment as Experiment); setVariants(data.variants as Variant[]); setChosen(""); setOutcome(""); setNotice("Генерирани са 3 Variants за преглед. Нищо не е изпратено."); }); }
  function select(id: string) { void run(async () => { await json(await fetch(`/api/ai/variants/${id}/select`, { method: "POST" })); setChosen(id); setExperiment(current => current ? { ...current, selected_variant_id: id } : current); setNotice("Variant е избран за ръчно изпращане."); }); }
  function markSent() { if (!chosen) return; void run(async () => { await json(await fetch(`/api/ai/variants/${chosen}/sent`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ selected: true }) })); setVariants(current => current.map(v => v.id === chosen ? { ...v, sent: true } : v)); setNotice("Маркирано като изпратено. Sales Copilot не изпрати съобщението."); }); }
  function record() { if (!chosen || !outcome) return; void run(async () => { const data = await json(await fetch(`/api/ai/variants/${chosen}/outcomes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ outcomeType: outcome }) })); setNotice(data.duplicate ? "Този Outcome вече е записан." : `Записан Outcome: ${outcomeLabel[outcome] || outcome.replaceAll("_", " ")}.`); }); }
  function reviewSuggestion(id: string, action: "confirm" | "reject") { void run(async () => { await json(await fetch(`/api/ai/outcome-suggestions/${id}/${action}`, { method: "POST" })); refreshSuggestions(); setNotice(action === "confirm" ? "Outcome е потвърден." : "Предложението е скрито."); }); }
  function decideInbound() { if (!inboundText.trim()) return; void run(async () => { const data = await json(await fetch("/api/ai/replies/decide", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId, message: inboundText }) })); setReplyDecision(data.decision as ReplyDecision); }); }
  const current = variants.find(v => v.id === chosen);
  return <section className="learning-panel"><div className="panel-heading"><div><span className="overline">OUTCOME LEARNING</span><h3>Learning и Experiments</h3><p>Сравнявай Strategy и записвай реални Outcomes.</p></div><button className="secondary" onClick={generate} disabled={busy}><Sparkles size={14}/>{busy && !experiment ? "Зареждане…" : "Генерирай 3 Variants"}</button></div>
    {error && <div className="form-error" role="alert">{error}</div>}{notice && <div className="finder-notice" role="status"><Check size={14}/>{notice}</div>}
    <div className="learning-suggestions"><b>Reply decision</b><div className="suggestion-row"><input aria-label="Входящо съобщение от Lead" placeholder="Постави входящо съобщение от Lead…" value={inboundText} onChange={event => setInboundText(event.target.value)} disabled={busy}/><button className="secondary" disabled={busy || !inboundText.trim()} onClick={decideInbound}>Класифицирай</button></div>{replyDecision && <div className="suggestion-row"><span><b>{replyDecision.mode}</b> · {replyDecision.intent} · {replyDecision.reason}</span>{replyDecision.mode === "HUMAN_REQUIRED" && <span className="sent-tag">Нужен е преглед от човек</span>}</div>}<p className="composer-hint">Автоматичното изпращане е изключено. Прегледай, редактирай и изпрати ръчно.</p></div>
    {style && <div className="learning-suggestions"><b>Личен стил</b><div className="suggestion-row"><span><b>Статус:</b> {style.status}</span><span><b>Използвани примери:</b> {style.sample_count}</span></div>{style.sample_count >= 5 && <p className="composer-hint">{style.profile.preferredLength === "short" ? "кратки съобщения" : "разнообразна дължина"} · {style.profile.preferredTone} тон · {style.profile.greetingStyle === "minimal" ? "минимален поздрав" : "естествен поздрав"} · {style.profile.emojiUsage === "rare" ? "рядко emoji" : "умерено emoji"}</p>}</div>}
    {suggestions.length > 0 && <div className="learning-suggestions"><b>Чакащи Reply предложения</b>{suggestions.map(s => <div className="suggestion-row" key={s.id}><span>{s.suggested_outcomes.map(o => `${outcomeLabel[o.outcome] || o.outcome.replaceAll("_", " ")} (${Math.round(o.confidence * 100)}%)`).join(" · ")}</span><button className="secondary" disabled={busy} onClick={() => reviewSuggestion(s.id, "confirm")}>Потвърди</button><button className="secondary" disabled={busy} onClick={() => reviewSuggestion(s.id, "reject")}>Скрий</button></div>)}</div>}
    {!performance.some(row => row.meaningful) && <p className="learning-insufficient">Недостатъчно данни — нужни са поне 10 изпратени Variants за Strategy.</p>}
    {experiment && <><div className="variant-list">{variants.map(variant => <article key={variant.id} className={`variant-card ${chosen === variant.id ? "chosen" : ""}`}><div className="variant-header"><b>Variant {variant.variant_key}</b>{experiment.recommended_variant_id === variant.id && <span className="recommended">Препоръчано</span>}</div><p>{variant.message}</p><div className="variant-footer"><span>{[variant.strategy_metadata.openerType, variant.strategy_metadata.responseStrategy, variant.strategy_metadata.ctaType, variant.strategy_metadata.tone, variant.strategy_metadata.lengthClass].filter(Boolean).map(value => value!.replaceAll("_", " ")).join(" · ")}</span><button className="secondary" disabled={busy} onClick={() => select(variant.id)}>{chosen === variant.id ? "Избран" : "Избери"}</button></div>{variant.sent && <span className="sent-tag">Маркирано като изпратено</span>}</article>)}</div><div className="learning-actions"><button className="secondary" disabled={busy || !chosen || !!current?.sent} onClick={markSent}>Маркирай като изпратено</button><select aria-label="Outcome тип" value={outcome} onChange={e => setOutcome(e.target.value)} disabled={!current?.sent || busy}><option value="">Избери Outcome</option>{outcomes.map(type => <option key={type} value={type}>{outcomeLabel[type] || type.replaceAll("_", " ")}</option>)}</select><button className="primary" disabled={!current?.sent || !outcome || busy} onClick={record}>Запиши Outcome</button></div><p className="composer-hint">Изборът или записът на Variant не изпраща Instagram съобщение. Изпрати ръчно преди маркиране.</p></>}
  </section>;
}
