"use client";
import { useEffect, useState } from "react";
import { Check, Sparkles } from "lucide-react";
type Variant = { id: string; variant_key: string; message: string; strategy_metadata: { openerType: string; ctaType: string; tone: string; personalizationType: string; lengthClass: string }; selected: boolean; sent: boolean };
type Experiment = { id: string; recommended_variant_id: string | null; selected_variant_id: string | null };
type Performance = { sentCount: number; replyCount: number; meaningful: boolean; label: string };
const outcomes = ["no_reply", "reply_neutral", "reply_positive", "reply_negative", "not_interested", "asks_price", "asks_demo", "asks_more_info", "meeting_booked", "converted", "blocked"];
async function json(response: Response) { const body = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(body.error || "Request failed.")); return body; }
export default function LearningPanel({ leadId }: { leadId: string }) {
  const [experiment, setExperiment] = useState<Experiment | null>(null); const [variants, setVariants] = useState<Variant[]>([]); const [chosen, setChosen] = useState(""); const [outcome, setOutcome] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [performance, setPerformance] = useState<Performance[]>([]);
  useEffect(() => { setExperiment(null); setVariants([]); setChosen(""); setOutcome(""); setNotice(""); fetch("/api/ai/performance").then(json).then(data => setPerformance(data.performance as Performance[])).catch(() => setPerformance([])); }, [leadId]);
  async function run(action: () => Promise<void>) { setBusy(true); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update experiment."); } finally { setBusy(false); } }
  function generate() { void run(async () => { const data = await json(await fetch("/api/ai/experiments/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId }) })); const next = data.experiment as Experiment; setExperiment(next); setVariants(data.variants as Variant[]); setChosen(""); setOutcome(""); setNotice("Three variants generated for review. Nothing has been sent."); }); }
  function select(id: string) { void run(async () => { await json(await fetch(`/api/ai/variants/${id}/select`, { method: "POST" })); setChosen(id); setExperiment(current => current ? { ...current, selected_variant_id: id } : current); setNotice("Variant selected for manual outreach."); }); }
  function markSent() { if (!chosen) return; void run(async () => { await json(await fetch(`/api/ai/variants/${chosen}/sent`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ selected: true }) })); setVariants(current => current.map(v => v.id === chosen ? { ...v, sent: true } : v)); setNotice("Recorded as sent. Sales Copilot did not send a message."); }); }
  function record() { if (!chosen || !outcome) return; void run(async () => { const data = await json(await fetch(`/api/ai/variants/${chosen}/outcomes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ outcomeType: outcome }) })); setNotice(data.duplicate ? "This outcome was already recorded for this variant." : `Recorded ${outcome.replaceAll("_", " ")}.`); }); }
  const current = variants.find(v => v.id === chosen);
  return <section className="learning-panel"><div className="panel-heading"><div><span className="overline">OUTCOME LEARNING</span><h3>Message experiments</h3><p>Compare strategies, choose freely, and record real outcomes.</p></div><button className="secondary" onClick={generate} disabled={busy}><Sparkles size={14}/>{busy && !experiment ? "Generating…" : "Generate 3 variants"}</button></div>
    {error && <div className="form-error" role="alert">{error}</div>}{notice && <div className="finder-notice" role="status"><Check size={14}/>{notice}</div>}
    {!performance.some(row => row.meaningful) && <p className="learning-insufficient">Insufficient data — at least 10 sent variants per strategy are needed before historical performance is meaningful.</p>}
    {experiment && <><div className="variant-list">{variants.map(variant => <article key={variant.id} className={`variant-card ${chosen === variant.id ? "chosen" : ""}`}><div className="variant-header"><b>Variant {variant.variant_key}</b>{experiment.recommended_variant_id === variant.id && <span className="recommended">Recommended</span>}</div><p>{variant.message}</p><div className="variant-footer"><span>{[variant.strategy_metadata.openerType, variant.strategy_metadata.ctaType, variant.strategy_metadata.tone, variant.strategy_metadata.lengthClass].map(value => value.replaceAll("_", " ")).join(" · ")}</span><button className="secondary" disabled={busy} onClick={() => select(variant.id)}>{chosen === variant.id ? "Selected" : "Select"}</button></div>{variant.sent && <span className="sent-tag">Recorded as sent</span>}</article>)}</div><div className="learning-actions"><button className="secondary" disabled={busy || !chosen || !!current?.sent} onClick={markSent}>Mark selected as sent</button><select aria-label="Outcome type" value={outcome} onChange={e => setOutcome(e.target.value)} disabled={!current?.sent || busy}><option value="">Choose outcome</option>{outcomes.map(type => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select><button className="primary" disabled={!current?.sent || !outcome || busy} onClick={record}>Record outcome</button></div><p className="composer-hint">Selecting or recording a variant never sends an Instagram message. Send manually before marking it as sent.</p></>}
  </section>;
}
