import { supabaseRequest } from "@/src/lib/supabase/server";
import type { BusinessProfile, KnowledgeItem, KnowledgeSource, KnowledgeStatus } from "./types";

const scope = "app_id=eq.sales_copilot";
const relevant = (message: string) => { const text = message.toLowerCase(); const categories = new Set<string>(); if (/price|cost|pricing|quote|discount|cheaper|eur|usd|лв|цена|отстъп/i.test(text)) ["pricing", "discounts", "products_services"].forEach(v => categories.add(v)); if (/instagram|tiktok|facebook|youtube|linkedin|platform|поддърж/i.test(text)) ["supported_platforms", "capabilities", "limitations", "integrations"].forEach(v => categories.add(v)); if (/guarantee|sales|revenue|гарант|продажб/i.test(text)) ["guarantees", "limitations", "escalation_rules"].forEach(v => categories.add(v)); if (/book|demo|schedule|meeting|час|демо/i.test(text)) ["demos", "booking", "timelines"].forEach(v => categories.add(v)); return categories; };
export async function listKnowledge(includeInactive = true) { return supabaseRequest<KnowledgeItem[]>(`sales_business_knowledge?${scope}&select=*&order=category.asc,key.asc${includeInactive ? "" : "&status=eq.VERIFIED"}`); }
export async function getKnowledge(id: string) { const rows = await supabaseRequest<KnowledgeItem[]>(`sales_business_knowledge?id=eq.${encodeURIComponent(id)}&${scope}&select=*`); return rows[0] || null; }
export async function createKnowledge(input: { category: string; key: string; title: string; value: unknown; status?: KnowledgeStatus; confidence?: number; source?: KnowledgeSource; notes?: string | null }) {
  const status = input.status || "UNVERIFIED"; const existing = await supabaseRequest<KnowledgeItem[]>(`sales_business_knowledge?${scope}&category=eq.${encodeURIComponent(input.category)}&key=eq.${encodeURIComponent(input.key)}&select=*`);
  const current = existing[0];
  if (current && current.status === "VERIFIED" && status === "VERIFIED" && JSON.stringify(current.value) !== JSON.stringify(input.value)) throw new Error("Conflicting verified knowledge exists for this category and key.");
  if (current) return updateKnowledge(current.id, { title: input.title, value: input.value, status, confidence: input.confidence, source: input.source, notes: input.notes || null });
  const rows = await supabaseRequest<KnowledgeItem[]>("sales_business_knowledge", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", category: input.category, key: input.key, title: input.title, value: input.value, status, confidence: Math.max(0, Math.min(1, input.confidence ?? (status === "VERIFIED" ? 1 : 0.4))), source: input.source || "manual", notes: input.notes || null }) }); return rows[0];
}
export async function updateKnowledge(id: string, patch: Partial<Pick<KnowledgeItem, "category" | "key" | "title" | "value" | "status" | "confidence" | "source" | "notes">>) { if (patch.status === "VERIFIED" && patch.category && patch.key && patch.value !== undefined) { const conflicts = await supabaseRequest<KnowledgeItem[]>(`sales_business_knowledge?${scope}&category=eq.${encodeURIComponent(patch.category)}&key=eq.${encodeURIComponent(patch.key)}&status=eq.VERIFIED&id=neq.${encodeURIComponent(id)}&select=*`); if (conflicts.some(item => JSON.stringify(item.value) !== JSON.stringify(patch.value))) throw new Error("Conflicting verified knowledge exists for this category and key."); } const rows = await supabaseRequest<KnowledgeItem[]>(`sales_business_knowledge?id=eq.${encodeURIComponent(id)}&${scope}`, { method: "PATCH", body: JSON.stringify({ ...patch, updated_at: new Date().toISOString() }) }); return rows[0] || null; }
export async function deleteKnowledge(id: string) { const existing = await getKnowledge(id); if (!existing) return null; const rows = await supabaseRequest<KnowledgeItem[]>(`sales_business_knowledge?id=eq.${encodeURIComponent(id)}&${scope}`, { method: "DELETE" }); return rows[0] || existing; }
export async function getVerifiedRelevantKnowledge(message: string) { const rows = await listKnowledge(false); const categories = relevant(message); const selected = rows.filter(item => categories.has(item.category)); return { items: selected, refs: selected.map(item => item.id), context: selected.slice(0, 8).map(item => `${item.category}.${item.key}: ${JSON.stringify(item.value)}`).join("\n") }; }
export async function knowledgeReadiness(intent: string, message: string) { const result = await getVerifiedRelevantKnowledge(message); const missing: string[] = []; if (intent === "asks_price" && !result.items.some(item => item.category === "pricing")) missing.push("pricing"); if (intent === "capability_faq" && /instagram|tiktok|facebook|youtube|linkedin|platform|поддърж/i.test(message) && !result.items.some(item => ["supported_platforms", "capabilities"].includes(item.category))) missing.push("platform capability"); return { eligible: missing.length === 0, missingKnowledge: missing, ...result }; }
export async function getBusinessProfile() { const rows = await supabaseRequest<BusinessProfile[]>(`sales_business_profile?${scope}&select=*&limit=1`); return rows[0] || null; }
export async function updateBusinessProfile(patch: Partial<Omit<BusinessProfile, "id" | "app_id" | "updated_at">>) { const current = await getBusinessProfile(); if (current) return (await supabaseRequest<BusinessProfile[]>(`sales_business_profile?id=eq.${encodeURIComponent(current.id)}&${scope}`, { method: "PATCH", body: JSON.stringify({ ...patch, updated_at: new Date().toISOString() }) }))[0]; return (await supabaseRequest<BusinessProfile[]>("sales_business_profile", { method: "POST", body: JSON.stringify({ app_id: "sales_copilot", default_language: "bg", ...patch }) }))[0]; }
