import type { Candidate, CandidateEnrichment, EnrichedProfile } from "@/src/lib/lead-finder/service";

type RawProfile = { url?: unknown; username?: unknown; verified?: unknown; sourceUrl?: unknown };
type RawEnrichment = Record<string, RawProfile | undefined>;
type ResponseBody = { output_text?: string; output?: unknown[]; status?: string; incomplete_details?: { reason?: string }; error?: { message?: string } | string };
const platforms = ["website", "instagram", "tiktok", "facebook", "youtube", "linkedin", "x"] as const;
const schema = { type: "object", additionalProperties: false, required: [...platforms], properties: Object.fromEntries(platforms.map(platform => [platform, { type: "object", additionalProperties: false, required: ["url", "username", "verified", "sourceUrl"], properties: { url: { type: "string" }, username: { type: "string" }, verified: { type: "boolean" }, sourceUrl: { type: "string" } } }])) };
const emptyProfile = (): EnrichedProfile => ({ url: "", username: "", verified: false, sourceUrl: "" });
function extractText(body: ResponseBody): string { if (typeof body.output_text === "string" && body.output_text.trim()) return body.output_text.trim(); const texts: string[] = []; const visit = (value: unknown) => { if (!value || typeof value !== "object") return; if (Array.isArray(value)) return value.forEach(visit); const item = value as Record<string, unknown>; const type = typeof item.type === "string" ? item.type : ""; if (type === "reasoning" || type.includes("tool") || type.includes("call")) return; if ((type === "output_text" || type === "text") && typeof item.text === "string") texts.push(item.text); if (Array.isArray(item.content)) visit(item.content); }; visit(body.output); return texts.join("\n").trim(); }
function publicUrl(value: unknown): value is string { return typeof value === "string" && /^https?:\/\/[^\s]+$/i.test(value); }
function cleanProfile(value: RawProfile | undefined): EnrichedProfile { if (!value || value.verified !== true || !publicUrl(value.url) || !publicUrl(value.sourceUrl)) return emptyProfile(); return { url: value.url, username: typeof value.username === "string" ? value.username : "", verified: true, sourceUrl: value.sourceUrl }; }
export async function enrichCandidate(candidate: Candidate): Promise<CandidateEnrichment> {
  const key = process.env.OPENAI_API_KEY?.trim(); if (!key) throw new Error("Lead Finder enrichment requires OPENAI_API_KEY.");
  const identity = JSON.stringify({ business_name: candidate.business_name, location: candidate.location, website: candidate.website, username: candidate.username, profile_url: candidate.profile_url, category: candidate.category, source_urls: candidate.source_urls });
  const instruction = `Enrich this existing business with verified public profiles across website, Instagram, TikTok, Facebook, YouTube, LinkedIn, and X. Use public web search once and return exactly the JSON schema. Match identity using the full business name, city, domain, username, and cross-links. Mark verified true only when public evidence strongly ties the profile to this same business. Prefer official website cross-links, then the official profile, then reputable public listings. Never guess or invent URLs. Unknown or ambiguous platforms must use empty strings and verified false. Every verified profile needs a valid HTTP(S) sourceUrl. Candidate identity: ${identity}`;
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` }, body: JSON.stringify({ model: process.env.OPENAI_ENRICHMENT_MODEL?.trim() || "gpt-4o-mini", tools: [{ type: "web_search" }], input: [{ role: "system", content: [{ type: "input_text", text: "You are a careful business identity verification assistant." }] }, { role: "user", content: [{ type: "input_text", text: instruction }] }], max_output_tokens: 1800, text: { format: { type: "json_schema", name: "lead_finder_enrichment", strict: true, schema } } }), cache: "no-store" });
  const body = await response.json().catch(() => null) as ResponseBody | null; if (!response.ok) { const error = body?.error; throw new Error(`Lead Finder enrichment provider request failed (${response.status}): ${typeof error === "string" ? error : error?.message || "request failed"}`); }
  const raw = extractText(body || {}); if (!raw) throw new Error(`Lead Finder enrichment returned no final text${body?.status === "incomplete" ? `: ${body.incomplete_details?.reason || "incomplete response"}` : "."}`);
  let parsed: RawEnrichment; try { parsed = JSON.parse(raw) as RawEnrichment; } catch { throw new Error("Lead Finder enrichment returned malformed structured JSON."); }
  return Object.fromEntries(platforms.map(platform => [platform, cleanProfile(parsed[platform])])) as CandidateEnrichment;
}
