import type { Candidate } from "@/src/lib/lead-finder/service";

type FinderResult = { answer: string; candidates: Array<Omit<Candidate, "id">> };
type ResponsesBody = { output_text?: string; output?: unknown[]; error?: { message?: string } | string };
const schema = { type: "object", additionalProperties: false, required: ["answer", "candidates"], properties: { answer: { type: "string" }, candidates: { type: "array", items: { type: "object", additionalProperties: false, required: ["business_name", "platform", "username", "profile_url", "website", "location", "category", "short_description", "why_relevant", "public_contact_method", "source_urls", "confidence"], properties: { business_name: { type: "string" }, platform: { type: "string" }, username: { type: "string" }, profile_url: { type: "string" }, website: { type: "string" }, location: { type: "string" }, category: { type: "string" }, short_description: { type: "string" }, why_relevant: { type: "string" }, public_contact_method: { type: "string" }, source_urls: { type: "array", items: { type: "string" } }, confidence: { type: "number" } } } } } };
const outputText = (body: ResponsesBody) => body.output_text || (body.output || []).flatMap(item => { const value = item as { content?: Array<{ text?: string }> }; return value.content || []; }).map(part => part.text || "").join("\n").trim();
const sourceUrls = (body: ResponsesBody) => { const urls = new Set<string>(); const scan = (value: unknown) => { if (!value || typeof value !== "object") return; if (Array.isArray(value)) return value.forEach(scan); const object = value as Record<string, unknown>; const annotation = object.annotation_type === "url_citation" || object.type === "url_citation"; const url = object.url; if (annotation && typeof url === "string" && /^https?:\/\//.test(url)) urls.add(url); Object.values(object).forEach(scan); }; scan(body.output); return [...urls]; };
function validCandidates(value: unknown): Array<Omit<Candidate, "id">> { const list = value && typeof value === "object" && Array.isArray((value as FinderResult).candidates) ? (value as FinderResult).candidates : []; return list.filter(candidate => candidate && typeof candidate.business_name === "string" && Array.isArray(candidate.source_urls) && candidate.source_urls.some(url => typeof url === "string" && /^https?:\/\//.test(url))).map(candidate => ({ business_name: candidate.business_name, platform: candidate.platform || null, username: candidate.username || null, profile_url: candidate.profile_url || null, website: candidate.website || null, location: candidate.location || null, category: candidate.category || null, short_description: candidate.short_description || null, why_relevant: candidate.why_relevant || null, public_contact_method: candidate.public_contact_method || null, source_urls: candidate.source_urls.filter(url => /^https?:\/\//.test(url)), confidence: typeof candidate.confidence === "number" ? Math.max(0, Math.min(1, candidate.confidence)) : null })); }
export async function searchWeb(query: string, history: Array<{ role: "user" | "assistant"; content: string }>): Promise<FinderResult> {
  const key = process.env.OPENAI_API_KEY?.trim(); if (!key) throw new Error("Lead Finder requires OPENAI_API_KEY.");
  const input = [{ role: "system", content: [{ type: "input_text", text: "You are Sales Copilot Lead Finder. Use public web search only. Find real businesses matching the request and return exactly the JSON schema. Every candidate must have at least one real public source URL. Never invent usernames, profiles, facts, counts, revenue, or contact volume. Use empty strings for unverified fields. Clearly separate facts from inferences in why_relevant. Keep the answer concise." }] }, ...history.slice(-10).map(message => ({ role: message.role, content: [{ type: "input_text", text: message.content }] })), { role: "user", content: [{ type: "input_text", text: query }] }];
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` }, body: JSON.stringify({ model: process.env.OPENAI_LEAD_FINDER_MODEL?.trim() || "gpt-5-mini", tools: [{ type: "web_search" }], input, max_output_tokens: 2200, text: { format: { type: "json_schema", name: "lead_finder_results", strict: true, schema } } }), cache: "no-store" });
  const body = await response.json().catch(() => null) as ResponsesBody | null; if (!response.ok) { const error = body?.error; throw new Error(`Lead Finder provider ${response.status}: ${typeof error === "string" ? error : error?.message || "request failed"}`); }
  const raw = outputText(body || {}); let parsed: Partial<FinderResult>; try { parsed = JSON.parse(raw) as Partial<FinderResult>; } catch { throw new Error("Lead Finder returned malformed structured results. Try a narrower search."); }
  const candidates = validCandidates(parsed); if (!parsed.answer || !candidates.length) return { answer: parsed.answer || "I could not find verified candidates for that request.", candidates };
  const citations = sourceUrls(body || {}); return { answer: parsed.answer, candidates: candidates.map(candidate => ({ ...candidate, source_urls: [...new Set([...candidate.source_urls, ...citations.filter(url => candidate.source_urls.includes(url))])] })) };
}
